kind: ConfigMap
apiVersion: v1
metadata:
  name: user-api-gateway
  namespace: saas-it-cstg
data:
  application.yml: |-
    resilience4j:
      circuitbreaker:
        configs:
          default:
            failureRateThreshold: 100
            registerHealthIndicator: true
            slidingWindowType: COUNT_BASED
            waitDurationInOpenState: 60000
            slidingWindowSize: 2
            permittedNumberOfCallsInHalfOpenState: 1

    resilience4j.timelimiter:
      configs:
        default:
          cancelRunningFuture: false
          timeoutDuration: 30s

    spring:
      cloud:
        gateway:
          httpclient:
            connect-timeout: 1000
            response-timeout: 30s
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders:
                  - Authorization
          routes:
            - id: userProfileService
              uri: http://user-profile-service-wdc-saas-it-cstg.tkg.vmware.com
              filters:
              - BasicAuth=${ups.auth.username}:${ups.auth.password}
              - RewritePath=/ups/(?<segment>.*), /$\{segment}
              - name: CircuitBreaker
                args:
                  routeId: userProfileService-fallback
                  name: userProfileService-fallback
                  fallbackUri: forward:/fallback/ups/**
                  statusCodes:
                  - 500
                  - 503
                  - 401
              - name: Retry
                args:
                  retries: 3
                  statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT,UNAUTHORIZED
                  series: SERVER_ERROR
                  methods: GET,POST,PUT,DELETE
                  exceptions: org.springframework.cloud.gateway.support.TimeoutException,java.net.ConnectException
                  backoff:
                    firstBackoff: 1000ms
                    factor: 2
                    basedOnPreviousValue: true
              predicates:
              - Path=/ups/**
            - id: saasUserService
              uri: http://saasuserservicev2-wdc-saas-it-cstg.tkg.vmware.com
              filters:
                - name: CircuitBreaker
                  args:
                    routeId: saasUserService-fallback
                    name: saasUserService-fallback
                    fallbackUri: forward:/fallback/**
                - name: Retry
                  args:
                    retries: 3
                    methods: GET,POST,PUT,DELETE
                    exceptions: org.springframework.cloud.gateway.support.TimeoutException,java.net.ConnectException
                    backoff:
                        firstBackoff: 1000ms
                        factor: 2
                        basedOnPreviousValue: true
              predicates:
                - Path=/v2/users/**
            - id: gateway-fallback
              uri: http://10.224.230.23:80
              filters:
                - PathResolver=/fallback/(?<segment>.*), /$\{segment}
              predicates:
                - Path=/fallback/**
    status.date.format: "MM.dd.yyyy HH:mm:ss"
    management.metrics.export.wavefront.enabled: true
    management.metrics.export.wavefront.uri: proxy://wvf-nprd-wdcpxy.vmware.com:2878
    management.metrics.export.wavefront.step: 10s
    management.metrics.export.wavefront.source: user-api-gateway-cstage-tkg-wdc-np
    management.metrics.use-global-registry: false
    wavefront.directIngestionEnabled: false
    wavefront.application.name: SCG-POC
    wavefront.application.service: user-api-gateway
    wavefront.application.cluster: cstg-wdc

