kind: ConfigMap
apiVersion: v1
metadata:
  name: user-api-gateway
  namespace: saas-it-cstg
data:
  application.yml: |-
    resilience4j:
      circuitbreaker:
        configs:
          default:
            failureRateThreshold: 100
            registerHealthIndicator: true
            slidingWindowType: COUNT_BASED
            waitDurationInOpenState: 60000
            slidingWindowSize: 2
            permittedNumberOfCallsInHalfOpenState: 1
            recordExceptions:
              - java.net.ConnectException
              - javax.net.ssl.SSLHandshakeException
              - org.springframework.cloud.gateway.support.TimeoutException
        instances:
          userProfileService-fallback:
            failureRateThreshold: 100
            registerHealthIndicator: true
            slidingWindowType: COUNT_BASED
            waitDurationInOpenState: 60s
            slidingWindowSize: 3
            permittedNumberOfCallsInHalfOpenState: 2
            recordExceptions:
              - java.net.ConnectException
              - javax.net.ssl.SSLHandshakeException
              - org.springframework.cloud.gateway.support.TimeoutException

    resilience4j.timelimiter:
      configs:
        default:
          cancelRunningFuture: false
          timeoutDuration: 30s

    spring:
      cloud:
        gateway:
          httpclient:
            connect-timeout: 1000
            response-timeout: 30s
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders:
                  - Authorization
          routes:
            - id: userProfileService
              uri: http://user-profile-service-sc2-saas-it-cstg.tkg.vmware.com
              filters:
              - BasicAuth=${ups.auth.username}:${ups.auth.password}
              - RewritePath=/ups/(?<segment>.*), /$\{segment}
              - name: CircuitBreaker
                args:
                  routeId: userProfileService-fallback
                  name: userProfileService-fallback
                  fallbackUri: forward:/fallback/ups/**
              - name: Retry
                args:
                  retries: 3
                  methods: GET,POST,PUT,DELETE
                  exceptions: org.springframework.cloud.gateway.support.TimeoutException,java.net.ConnectException
                  backoff:
                    firstBackoff: 1000ms
                    factor: 2
                    basedOnPreviousValue: true
              predicates:
              - Path=/ups/**
            - id: saasUserService
              uri: http://saasuserservicev2-sc2-saas-it-cstg.tkg.vmware.com
              filters:
                - name: CircuitBreaker
                  args:
                    routeId: saasUserService-fallback
                    name: saasUserService-fallback
                    fallbackUri: forward:/fallback/v2/users/**
                - name: Retry
                  args:
                    retries: 3
                    methods: GET,POST,PUT,DELETE
                    exceptions: org.springframework.cloud.gateway.support.TimeoutException,java.net.ConnectException
                    backoff:
                        firstBackoff: 1000ms
                        factor: 2
                        basedOnPreviousValue: true
              predicates:
                - Path=/v2/users/**
            - id: gateway-fallback
              uri: http://user-api-gateway-wdc-saas-it-cstg.tkg.vmware.com
              filters:
                - PathResolver=/fallback/(?<segment>.*), /$\{segment}
              predicates:
                - Path=/fallback/**
    status.date.format: "MM.dd.yyyy HH:mm:ss"
    management.metrics.export.wavefront.enabled: true
    management.metrics.export.wavefront.uri: proxy://wvf-nprd-wdcpxy.vmware.com:2878
    management.metrics.export.wavefront.step: 10s
    management.metrics.export.wavefront.source: user-api-gateway-cstage-tkg-sc2
    management.metrics.use-global-registry: false
    wavefront.directIngestionEnabled: false
    wavefront.application.name: SCG-POC
    wavefront.application.service: user-api-gateway
    wavefront.application.cluster: cstg-sc2
    logging.level.org.springframework.cloud.gateway.filter.factory: TRACE



