server.port: 8090
security:
  basic:
    enabled: true
  user:
    name: user
    password: userpass
spring:
  main:
    allow-circular-references: true
  cloud:
    gateway:
      routes:
        - id: serviceA
          uri: http://localhost:8080
          predicates:
            - Path=/api/**